### ISSUE TITLE
[도움요청 & 질문] GlideImage.kt 의 CircularProgressIndicator() 검토 요청

### ISSUE THREAD

**Issue by Luna828** [Team-Crackdown/TAVE-Android#12]
안녕하세요 @KanuKim97 님!~

GlideImage.kt 코드 분리를 완료하고,
GlideImage 안에 있는 loading composable의 CircularProgressIndicator의 디자인 상태 검토 부탁 드립니다. 

```
loading = {
            Box(
                modifier = modifier.size(20.dp),
                contentAlignment = Alignment.Center,
                content = {
                    CircularProgressIndicator(
                        strokeWidth = 4.dp
                    )
                }
            )
        },
```

현재 loading시, 아래의 사진과 같이 Image view가 너무 많은 관계로 디자인에 문제가 있어 보입니다. 
검토 후, 의견 주시면 감사하겠습니다!  
 ![image](https://github.com/Team-Crackdown/TAVE-Android/assets/93186591/3b97b0a3-177b-465d-82d4-1d33d733f27f)

**Comment by KanuKim97** [comment]
스켈레톤 이미지 로딩방식 구현 및 처리 완료로 인한 Close
