### ISSUE TITLE
[도움요청 & 질문] OutlinedTextField Height 설정 값 도움 요청

### ISSUE THREAD

**Issue by Luna828** [Team-Crackdown/TAVE-Android#4]
items/profile/UpdateTextField의 
UpdateTextFieldForIntro OutlinedTextField height 설정값에 대한 도움요청 입니다!

![image](https://github.com/Team-Crackdown/TAVE-Android/assets/93186591/d3179fc2-becd-46d7-88c0-e17d50ae7f3a)

**Comment by KanuKim97** [comment]
#10 의 Issue와 중복되는 문제로 보입니다 따라서 이 Issue를 Close합니다.
