### ISSUE TITLE
[수정 요청 & 질문] UserBadge Item의 TextContent 정렬 문제

### ISSUE THREAD

**Issue by KanuKim97** [Team-Crackdown/TAVE-Android#8]
**요청한 기능이 어떤 문제 및 어떤 향상을 가져다 주는지 기술해 주세요.**
 기존 UserBadge Item의 TextContent가 중앙으로 정렬되지 않은 모습을 띄고 있습니다.
이에 따라 Code 재구성 이 필요하다고 생각하여 Issue 등록을 하였습니다.

**당신이 고려한 대안을 설명해주세요**
Card를 사용하지 않고 Box를 사용해보는 대안을 고려 중입니다.

**추가 질문**
UserBadge Composable의 코드의 Text()에
```
style = TextStyle(
    platformStyle = PlatformTextStyle(includeFontPadding = false),
    lineHeight = 2.5.em
)
```
코드를 사용하셨습니다.
이 코드를 사용하게 된 계기와 이유가 있을까요?
답변 부탁드립니다 @Luna828 님!

**Comment by Luna828** [comment]
```
style = TextStyle(
    platformStyle = PlatformTextStyle(includeFontPadding = false),
    lineHeight = 2.5.em
)
```
코드를 사용한 이유는 Notosanskr 폰트를 사용한 이후 글자가 사라지는 것 방지를 위해 텍스트 크기를 맞추기 위한 것에 대한 방안이었습니다. 
하지만, 아직 중앙 정렬에대한 답은 찾지 못하였기 때문에 Box 로 변경해보겠습니다.

**Comment by KanuKim97** [comment]
> ```
> style = TextStyle(
>     platformStyle = PlatformTextStyle(includeFontPadding = false),
>     lineHeight = 2.5.em
> )
> ```
> 
> 코드를 사용한 이유는 Notosanskr 폰트를 사용한 이후 글자가 사라지는 것 방지를 위해 텍스트 크기를 맞추기 위한 것에 대한 방안이었습니다. 하지만, 아직 중앙 정렬에대한 답은 찾지 못하였기 때문에 Box 로 변경해보겠습니다.

넵!  답변 감사합니다 @Luna828 님!

**Comment by KanuKim97** [comment]
#9 PR로 인한 Issue Close
